sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - CHEF_VERSION=current INSTANCE=default-amazonlinux
  - CHEF_VERSION=current INSTANCE=default-amazonlinux-2
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1404
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1604
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1804
  - CHEF_VERSION=current INSTANCE=default-debian-8
  - CHEF_VERSION=current INSTANCE=default-debian-9
  - CHEF_VERSION=current INSTANCE=default-fedora-latest
  - CHEF_VERSION=current INSTANCE=default-centos-6
  - CHEF_VERSION=current INSTANCE=default-centos-7
  - CHEF_VERSION=current INSTANCE=default-opensuse-leap
  - CHEF_VERSION=13 INSTANCE=default-amazonlinux
  - CHEF_VERSION=13 INSTANCE=default-ubuntu-1404
  - CHEF_VERSION=13 INSTANCE=default-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=default-ubuntu-1804
  - CHEF_VERSION=13 INSTANCE=default-debian-8
  - CHEF_VERSION=13 INSTANCE=default-debian-9
  - CHEF_VERSION=13 INSTANCE=default-fedora-latest
  - CHEF_VERSION=13 INSTANCE=default-centos-6
  - CHEF_VERSION=13 INSTANCE=default-centos-7
  - CHEF_VERSION=13 INSTANCE=default-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
